### ISSUE TITLE
Route path classes

### ISSUE THREAD

**Issue by billdami** [nathanhammond/ember-body-class#5]
It looks like the automatic route path classes were removed in this fork (i.e. https://github.com/stonecircle/ember-body-class/blob/master/addon/instance-initializers/body-class.js#L27), is that correct?

**Comment by nathanhammond** [comment]
That is correct, and intentional. Route path elements are not guaranteed to be unique which can result in significant issues.

If you wish to maintain *approximate* parity with the upstream code, you can [use the pattern described in the README](https://github.com/nathanhammond/ember-body-class#add-class-name-to-each-route).
